### PR TITLE
Revamped config & new bridge gateway to handle

### PR DESCRIPTION
**Pull request by FredBlo**
Hi @andesse ,

I was also experiencing some issues with the HueMagic node, therefore I wanted to give a try to yours :-)
I found it really interesting (thanks for it !).
When setting it up on my system, I also improved it...

I think the major update -to me- is the fact the bridge connector is now able to handle the overflow of call (i.e. when sending >5 commands per second to the bridge). It ensures all commands are successfully sent. The limitation of what I made (which is very basic queuing / retry) is that it does not guarantee all calls are received by the bridge in their initial order.
For example, if you send 8 requests for a single light point like 'on-off-on-off-on-off-on-off', these could be processed like
on-off-on-off-**off**-off-on-**on**, also meaning, in this case, light will remain on at the end while it should be off...

I let you see / check whether this can be of interest to you / your repository :-)

Other changes made fyi :
- Existing Subflows (Light, Button & Motion Sensor receivers) are now 'configurable' for easier integration in existing system
   - ID / RID is set in insert node config
- New subflow added 'Light Sender' to send commands to lamps easily, using node config :
   - ID / RID is set in inserted node config
   - type of light (light point or group of light)
- The 'bridge link' (receiver & sender) was revamped:
   - single centralized grouped nodes for all calls
   - handles 'overflows of calls' (i.e. when the HUE bridge refuses calls because it rate is > 5/sec, they are queued for repeat)
   - a return value is sent to allow continuing the flow after command was sent
- removed / merged the 'technical' subflows (only used in configuration part to find the ID's / RID's
- A bit of 'UI'
   - Re-organized nodes in groups to make it easier reading / configuring / accessing
   - Some comments are directly readable without opening them (i.e. double click on it)
   - added output names to subflows to easily know what to expect as output when reading flow using such nodes (without having to open subflow)
   - ...

### CODE REVIEW

**Comment by andesse** [comment]
@FredBlo wow, looks nice, thanks for the effort.

I don't really know what the patch links will do and what will happen when I merge it... never made it. Can you explain what will happen? 

I would add your flow as an additional file (probably as the main file in this repository), create a new version and add all your description to the readme. Mentioning, that you created a new approach for this repository. 

But I would keep all the existing files.

**Comment by andesse** [comment]
@FredBlo why do the outputs inside the subflows the Var Id „replace with discovered Id“ inside?
Is this necessary? If not it should be removed, otherwise it’s confusing.

**Review by andesse — COMMENTED** [review]
Everything seems to be working fine

**Comment by FredBlo** [comment]
@andesse the merge will simply take the difference, in this case I only added a file so it will add it too your main branch
But I see you already tested & discovered it :-)

**Comment by andesse** [comment]
@FredBlo i just was brave and clicked on it. 
Nice approach. Thanks

**Comment by FredBlo** [comment]
:-)

Fyi, I saw that you added a comment in the 'engine' file that *'Your need to have the option to save your context to file to get this work'*.
This is not necessary because the inject node is configured to automatically inject on deploy / server restart:
image

That's also why it has a -very- small '1' added to the node
image

This is a handy one in Node-RED :-)

**Comment by andesse** [comment]
@FredBlo lol, didnt recognize,  I changed the readme
Thanks

**Pull request merged**
